import socket
import ssl

# Setting up client server to communicate with the secure server
HOST = 'localhost'
PORT = 5005

# Load the server.pem SSL certificate generated by secure server
context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
context.load_verify_locations("server.pem")

# Creating a TCP socket for stream based connection
with socket.create_connection((HOST, PORT)) as sock:
    with context.wrap_socket(sock, server_hostname=HOST) as ssock:
        print("The client server has established secure connection with the secure server.")
        ssock.sendall(b"Hello, secure server, client server ready to communicate!")
        data = ssock.recv(1024)
        print(f"The client server received data from server: {data.decode()}")
